# Source: external-dns-resources/templates/cloudflare-secrets.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-secrets
  annotations:
    meta.helm.sh/release-name: 'external-dns-resources'
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: jx-vault
  data:
    - name: cloudflare_api_token
      key: secret/data/platform/external-dns/cloudflare
      property: cloudflare_api_token
