apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    autoMerge: true
    enabled: true
    schedule: 0 0 * * *
  cluster:
    azure:
      storage:
        storageAccountName: jxxyzdevcluster
    chartKind: pages
    chartRepository: https://property-xyz.github.io
    devEnvApprovers:
    - dicolasi
    - kannan1
    environmentGitOwner: property-xyz
    gitKind: github
    gitName: github
    gitServer: https://github.com
    provider: k8s
    registry: ghcr.io
  environments:
  - key: dev
    owner: property-xyz
    repository: dev_platform-cluster-azure
  - gitKind: github
    gitServer: https://github.com
    key: staging
    owner: property-xyz
    promotionStrategy: Auto
    remoteCluster: true
    repository: stage_platform-cluster
  - gitKind: github
    gitServer: https://github.com
    key: production
    owner: property-xyz
    promotionStrategy: Manual
    remoteCluster: true
    repository: prod_platform-cluster
  ingress:
    domain: dev.property.xyz
    externalDNS: true
    kind: ingress
    namespaceSubDomain: .
    tls:
      email: security@property.xyz
      enabled: true
      production: true
  pipelineUser:
    username: property-xyz-bot
  repository: bucketrepo
  secretStorage: vault
  storage:
  - name: logs
    url: azblob://logs
  terraformVault: true
  vault: {}
  webhook: lighthouse
