apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    autoMerge: true
    enabled: true
    schedule: 0 0 * * *
  cluster:
    azure:
      storage:
        storageAccountName: jxxyzdevcluster
    chartKind: pages
    chartRepository: https://github.com/property-xyz/property-xyz.github.io.git
    devEnvApprovers:
    - dicolasi
    - kannan1
    environmentGitOwner: property-xyz
    gitKind: github
    gitName: github
    gitServer: https://github.com
    provider: k8n
    registry: https://index.docker.io/v1/
  environments:
  - key: dev
    owner: property-xyz
    repository: dev_platform-cluster-azure
  - key: staging
  - key: production
  ingress:
    domain: dev.property.xyz
    externalDNS: true
    kind: ingress
    namespaceSubDomain: .
    tls:
      email: security@property.xyz
      enabled: true
      production: true
  pipelineUser:
    username: property-xyz-bot
  repository: bucketrepo
  secretStorage: vault
  storage:
  - name: logs
    url: azblob://logs
  terraformVault: true
  vault: {}
  webhook: lighthouse
