rbac:
  create: true
  global: true
args:
   - --delete-successful-after=5m
   - --delete-failed-after=5m
   - --delete-pending-pods-after=15m
   - --delete-evicted-pods-after=2m
   - --delete-orphaned-pods-after=1m
   - --legacy-mode=false
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 64Mi