# Source: platform-azure-demonset/templates/rbac.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: node-untaint
  annotations:
    meta.helm.sh/release-name: 'platform-azure-demonset'
  labels:
    gitops.jenkins-x.io/pipeline: 'cluster'
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["*"]
