# Source: platform-azure-demonset/templates/rbac.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: node-untaint
  annotations:
    meta.helm.sh/release-name: 'platform-azure-demonset'
  labels:
    gitops.jenkins-x.io/pipeline: 'cluster'
roleRef:
  kind: ClusterRole
  name: node-untaint
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: node-untaint
    namespace: kube-system
