filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: cert-manager
repositories:
- name: jetstack
  url: https://charts.jetstack.io
releases:
- chart: jetstack/cert-manager
  version: v1.8.0
  name: cert-manager
  values:
  - jx-values.yaml
  - ../../versionStream/charts/jetstack/cert-manager/values.yaml.gotmpl
- chart: ../../charts/cert-manager-resources
  name: cert-manager-resources
  values:
  - jx-values.yaml
templates: {}
renderedvalues: {}
