# Source: platform-frontend/templates/sa.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform-frontend-platform-frontend
  annotations:
    meta.helm.sh/release-name: 'platform-frontend'
  namespace: jx-staging
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
