# Source: platform-frontend/templates/secrets.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: platform-frontend-secrets
  namespace: jx-staging
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: jx-vault
  data:
    - name: GCP_KEY_FILE_BASE64
      key: secret/data/platform/frontend/secrets
      property: GCP_KEY_FILE_BASE64
    - name: XYZ_GOOGLE_ANALYTICS_KEY
      key: secret/data/platform/frontend/secrets
      property: XYZ_GOOGLE_ANALYTICS_KEY
    - name: XYZ_GOOGLE_MAPS_API_KEY
      key: secret/data/platform/frontend/secrets
      property: XYZ_GOOGLE_MAPS_API_KEY
    - name: XYZ_GOOGLE_TAG_MANAGER_ID
      key: secret/data/platform/frontend/secrets
      property: XYZ_GOOGLE_TAG_MANAGER_ID
    - name: XYZ_GOOGLE_TAG_MANAGER_AUTH
      key: secret/data/platform/frontend/secrets
      property: XYZ_GOOGLE_TAG_MANAGER_AUTH
    - name: OS_MAPS_API_KEY
      key: secret/data/platform/frontend/secrets
      property: OS_MAPS_API_KEY
    - name: KEYCLOAK_COOKIE_SECRET
      key: secret/data/platform/frontend/secrets
      property: KEYCLOAK_COOKIE_SECRET
    - name: POSTGRES_DB_CONNECTION_STRING
      key: secret/data/platform/frontend/secrets
      property: POSTGRES_DB_CONNECTION_STRING
  template:
    metadata:
      annotations:
        meta.helm.sh/release-name: 'platform-frontend'
    type: Opaque
