apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-secrets
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: jx-vault
  data:
    - name: cloudflare_api_token
      key: secret/data/platform/external-dns/cloudflare
      property: cloudflare_api_token