apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "{{ .Values.jxRequirements.ingress.tls.email }}"
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      # ACME DNS-01 provider configurations
    - dns01:
        cloudflare:
           email: "{{ .Values.jxRequirements.ingress.tls.email }}"
           apiTokenSecretRef:
             name: cloudflare-secrets
             key: cloudflare_api_token