filepath: ""
namespace: jx-production
repositories:
- name: dev
  url: https://property-xyz.github.io/property-xyz.github.io/
releases:
- chart: dev/data-seed
  version: 0.1.11
  name: data-seed
templates: {}
renderedvalues: {}
