filepath: ""
namespace: jx-production
repositories:
- name: dev
  url: https://property-xyz.github.io/property-xyz.github.io/
releases:
- chart: dev/data-rdf-client
  version: 0.0.9
  name: data-rdf-client
templates: {}
renderedvalues: {}
