# Source: jx-slack/templates/slack-token-secret.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: jx-slack
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: jx-vault
  data:
    - name: token
      key: secret/data/jx/slack
      property: token
  template:
    metadata:
      annotations:
        meta.helm.sh/release-name: 'jx-slack'
    type: Opaque
