apiVersion: gitops.jenkins-x.io/v1alpha1
kind: SourceConfig
metadata:
  creationTimestamp: null
spec:
  groups:
  - owner: property-xyz
    provider: https://github.com
    providerKind: github
    repositories:
    - name: data-avm-service
    - name: data-council-tax-service
    - name: data-demand-stats-service
    - name: data-epc-service
    - name: data-export-service
    - name: data-growth-stats-service
    - name: data-hmo-service
    - name: data-infinispan-cache
    - name: data-landregistry-sparql-client
    - name: data-outcode-stats-service
    - name: data-rdf-client
    - name: data-rent-demand-service
    - name: data-seed
    - name: data-uk-national-statistics
    - name: data-yield-stats-service
    - name: platform-azure-demonset
    - name: platform-frontend
    - name: platform-lambda-crm-integration
    - name: platform-lambda-mail-service
    - name: platform-postcodes-io-db
    - name: platform-search-service
    - name: prod_platform-cluster
    - name: stage_platform-cluster
    scheduler: in-repo
  slack:
    channel: '#jenkins-x-pipelines'
    kind: failureOrNextSuccess
    pipeline: release
