filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: jx
repositories:
- name: stable
  url: https://charts.helm.sh/stable
- name: bitnami
  url: https://charts.bitnami.com/bitnami
- name: jxgh
  url: https://jenkins-x-charts.github.io/repo
releases:
- chart: jxgh/jx-slack
  version: 0.0.66
  name: jx-slack
  values:
  - jx-values.yaml
- chart: ../../charts/external-dns-resources
  version: 1.0.0
  name: external-dns-resources
  values:
  - jx-values.yaml
- chart: bitnami/external-dns
  version: 6.0.2
  condition: jxRequirementsIngressExternalDNS.enabled
  name: external-dns
  values:
  - ../../values/external-dns/values.yaml.gotmpl
  - jx-values.yaml
  - ../../versionStream/charts/bitnami/external-dns/values.yaml.gotmpl
- chart: jxgh/jxboot-helmfile-resources
  version: 1.1.65
  name: jxboot-helmfile-resources
  values:
  - ../../versionStream/charts/jxgh/jxboot-helmfile-resources/values.yaml.gotmpl
  - jx-values.yaml
- chart: jxgh/jenkins-x-crds
  version: 3.0.12
  name: jenkins-x-crds
  values:
  - ../../versionStream/charts/jxgh/jenkins-x-crds/values.yaml.gotmpl
  - jx-values.yaml
- chart: jxgh/jx-pipelines-visualizer
  version: 1.8.0
  name: jx-pipelines-visualizer
  values:
  - ../../versionStream/charts/jxgh/jx-pipelines-visualizer/values.yaml.gotmpl
  - jx-values.yaml
- chart: jxgh/jx-preview
  version: 0.0.199
  name: jx-preview
  values:
  - jx-values.yaml
- chart: jxgh/lighthouse
  version: 1.5.14
  name: lighthouse
  values:
  - ../../versionStream/charts/jxgh/lighthouse/values.yaml.gotmpl
  - jx-values.yaml
- chart: jxgh/nexus
  version: 0.1.41
  name: nexus
  values:
  - ../../versionStream/charts/jxgh/nexus/values.yaml.gotmpl
  - jx-values.yaml
- chart: jxgh/jx-build-controller
  version: 0.3.15
  name: jx-build-controller
  values:
  - ../../versionStream/charts/jxgh/jx-build-controller/values.yaml.gotmpl
  - jx-values.yaml
- chart: jxgh/lighthouse-webui-plugin
  version: 0.1.7
  name: lighthouse-webui-plugin
  values:
  - ../../versionStream/charts/jxgh/lighthouse-webui-plugin/values.yaml.gotmpl
  - jx-values.yaml
templates: {}
renderedvalues: {}
