# Source: cert-manager-resources/templates/cluster-issuer.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  annotations:
    meta.helm.sh/release-name: 'cert-manager-resources'
  labels:
    gitops.jenkins-x.io/pipeline: 'cluster'
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "security@property.xyz"
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      # ACME DNS-01 provider configurations
      - dns01:
          cloudflare:
            email: "security@property.xyz"
            apiTokenSecretRef:
              name: cloudflare-secrets
              key: cloudflare_api_token
