# Source: cert-manager-resources/templates/cluster-issuer.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: zerossl-prod
  annotations:
    meta.helm.sh/release-name: 'cert-manager-resources'
  labels:
    gitops.jenkins-x.io/pipeline: 'cluster'
spec:
  acme:
    # The ACME server URL
    server: https://acme.zerossl.com/v2/DV90
    externalAccountBinding:
      keyID: 84rHaBv91-61-AmxptQtVw
      keySecretRef:
        name: zerossl-secrets
        key: eab_hmac_key
      keyAlgorithm: HS256
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: zerossl-prod
    solvers:
      # ACME DNS-01 provider configurations
      - dns01:
          cloudflare:
            email: "security@property.xyz"
            apiTokenSecretRef:
              name: cloudflare-secrets
              key: cloudflare_api_token
