# Source: platform-postcodes-io-db/templates/ksvc-api.yaml
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: platform-postcodes-io-db-api
  annotations:
    custom-hostname: postcodes
    meta.helm.sh/release-name: 'platform-postcodes-io-db'
  labels:
    app.kubernetes.io/name: platform-postcodes-io-db-api
    helm.sh/chart: platform-postcodes-io-db-0.1.3
    app.kubernetes.io/instance: platform-postcodes-io-db
    app.kubernetes.io/managed-by: Helm
    gitops.jenkins-x.io/pipeline: 'namespaces'
  namespace: jx-dev
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
    spec:
      containers:
        - name: platform-postcodes-io-db-api
          image: "idealpostcodes/postcodes.io:release-14.1.0"
          imagePullPolicy: "IfNotPresent"
          livenessProbe:
            httpGet:
              path: /
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          resources: {}
          env:
            - name: NODE_ENV
              value: production
            - name: POSTGRES_USER
              value: postcodesio
            - name: POSTGRES_DATABASE
              value: postcodesiodb
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: platform-postcodes-io-db-database
                  key: password
            - name: POSTGRES_HOST
              value: platform-postcodes-io-db-database
            - name: POSTGRES_PORT
              value: "5432"
          volumeMounts:
            - name: config
              mountPath: /usr/src/app/config/defaults.js
              subPath: defaults.js
      volumes:
        - name: config
          configMap:
            name: platform-postcodes-io-db-api
