# Source: platform-postcodes-io-db/templates/secrets.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: platform-postcodes-io-db-database
  labels:
    app.kubernetes.io/name: platform-postcodes-io-db-database
    helm.sh/chart: platform-postcodes-io-db-0.1.3
    app.kubernetes.io/instance: platform-postcodes-io-db
    app.kubernetes.io/managed-by: Helm
    gitops.jenkins-x.io/pipeline: 'namespaces'
  annotations:
    meta.helm.sh/release-name: 'platform-postcodes-io-db'
  namespace: jx-dev
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: jx-vault
  data:
    - name: password
      key: secret/data/postcodes-io/database/credentials
      property: password
