# Source: platform-postcodes-io-db/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-postcodes-io-db-api
  labels:
    app.kubernetes.io/name: platform-postcodes-io-db-api
    helm.sh/chart: platform-postcodes-io-db-0.1.3
    app.kubernetes.io/instance: platform-postcodes-io-db
    app.kubernetes.io/managed-by: Helm
    gitops.jenkins-x.io/pipeline: 'namespaces'
  annotations:
    meta.helm.sh/release-name: 'platform-postcodes-io-db'
  namespace: jx-dev
data:
  defaults.js: |-
    module.exports = {"bulkGeocode":{"geolocations":{"ASYNC_LIMIT":null,"MAX":100,"TIMEOUT":30000}},"bulkLookups":{"postcodes":{"ASYNC_LIMIT":null,"MAX":100,"TIMEOUT":30000}},"filterableAttributes":["postcode","quality","eastings","northings","country","nhs_ha","longitude","latitude","parliamentary_constituency","european_electoral_region","primary_care_trust","region","lsoa","msoa","incode","outcode","codes","admin_district","parish","admin_county","admin_ward","ccg","nuts","ced"],"nearest":{"limit":{"DEFAULT":10,"MAX":100},"radius":{"DEFAULT":100,"MAX":2000}},"nearestOutcodes":{"limit":{"DEFAULT":10,"MAX":100},"radius":{"DEFAULT":5000,"MAX":25000}},"placesContained":{"limit":{"DEFAULT":10,"MAX":100}},"placesNearest":{"limit":{"DEFAULT":10,"MAX":100},"radius":{"DEFAULT":1000,"MAX":10000}},"placesSearch":{"limit":{"DEFAULT":10,"MAX":100}},"search":{"limit":{"DEFAULT":10,"MAX":100}}};
