# Source: platform-postcodes-io-db/templates/service-database.yaml
apiVersion: v1
kind: Service
metadata:
  name: platform-postcodes-io-db-database
  labels:
    app.kubernetes.io/name: platform-postcodes-io-db-database
    helm.sh/chart: platform-postcodes-io-db-0.1.3
    app.kubernetes.io/instance: platform-postcodes-io-db
    app.kubernetes.io/managed-by: Helm
    gitops.jenkins-x.io/pipeline: 'namespaces'
  annotations:
    meta.helm.sh/release-name: 'platform-postcodes-io-db'
  namespace: jx-dev
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    app.kubernetes.io/name: platform-postcodes-io-db-database
    app.kubernetes.io/instance: platform-postcodes-io-db
