# Source: cert-manager-resources/templates/domain-certificate.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "tls-dev-property-xyz-p"
  labels:
    jenkins.io/letsencrypt-service: production
    gitops.jenkins-x.io/pipeline: 'namespaces'
  annotations:
    meta.helm.sh/release-name: 'cert-manager-resources'
  namespace: cert-manager
spec:
  secretName: "tls-dev-property-xyz-p"
  issuerRef:
    name: zerossl-prod
    kind: ClusterIssuer
  commonName: "*.dev.property.xyz"
  dnsNames:
    - "*.dev.property.xyz"
    - "dev.property.xyz"
