# Source: cert-manager-resources/templates/zerossl-secrets.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: zerossl-secrets
  annotations:
    meta.helm.sh/release-name: 'cert-manager-resources'
  namespace: cert-manager
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: jx-vault
  data:
    - name: eab_hmac_key
      key: secret/data/platform/cert-manager/zero-ssl
      property: eab_hmac_key
